name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [22]
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install

    - name: Run Biome Lint
      run: pnpm exec biome check

    - name: Run TypeScript Type Check
      run: pnpm exec tsc --noEmit

    - name: Run Tests
      run: pnpm test